version: "3"
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  redis:
    image: redis:7.0
    ports:
      - '16379:6379'
    volumes:
      - redis-data:/var/lib/redis/data

  web:
    build:
      context: .
      args:
        UID: "${USER_ID:-1000}"
        GID: "${GROUP_ID:-1000}"
    command: sh ./docker-entrypoint-web.sh
    volumes:
      - .:/webapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres-data:
  redis-data:
